import {createContext,useContext,useEffect,useMemo,useState,type ReactNode} from "react";
import {initialState} from "@/data/portal-data";
import type {AuditEntry,OrganisationId,PortalState,PortalUser,Role,Ticket} from "./portal-types";
type Store={state:PortalState;hydrated:boolean;signIn:(mode:"customer"|"platform")=>void;signOut:()=>void;setRole:(r:Role)=>void;setOrg:(o:OrganisationId)=>void;addTicket:(t:Ticket)=>void;updateTicket:(id:string,fn:(t:Ticket)=>Ticket)=>void;addUser:(u:PortalUser)=>void;updateUser:(id:string,fn:(u:PortalUser)=>PortalUser)=>void;viewArticle:(id:string)=>void;voteArticle:(id:string,v:string)=>void;setPreference:(k:"notifications"|"highContrast",v:boolean)=>void;patchState:(fn:(s:PortalState)=>PortalState)=>void;addAudit:(entry:Omit<AuditEntry,"id"|"at">)=>void;resetDemo:()=>void};
const Ctx=createContext<Store|null>(null);const KEY="health-it-portal-demo-v1";
const mergeState=(saved:Partial<PortalState>):PortalState=>({...initialState,...saved,draftNewStarterFields:saved.draftNewStarterFields??saved.newStarterFields??initialState.draftNewStarterFields,supportPrefill:saved.supportPrefill??null,tickets:saved.tickets?.map(t=>{const seed=initialState.tickets.find(x=>x.id===t.id);return {...t,priority:t.priority??seed?.priority??"Normal",assignedTo:t.assignedTo??seed?.assignedTo??"Unassigned",slaState:t.slaState??seed?.slaState??"On Track",queue:t.queue??seed?.queue??"Service Desk",lastSuccessfulSync:t.lastSuccessfulSync??seed?.lastSuccessfulSync??"11 Sep 2026, 13:20",pendingChanges:t.pendingChanges??seed?.pendingChanges??0,correlationId:t.correlationId??seed?.correlationId??`COR-${t.id}`,latestSource:t.latestSource??seed?.latestSource??"Portal"}})??initialState.tickets,users:saved.users?.map(u=>({...u,invitationStatus:u.invitationStatus??"Accepted",lastSignIn:u.lastSignIn??"11 Sep 2026, 08:42"}))??initialState.users});
export function PortalProvider({children}:{children:ReactNode}){const[state,setState]=useState(initialState);const[hydrated,setHydrated]=useState(false);useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setState(mergeState(JSON.parse(raw)));}catch{}setHydrated(true)},[]);useEffect(()=>{if(hydrated)localStorage.setItem(KEY,JSON.stringify(state))},[state,hydrated]);
 const audit=(entry:Omit<AuditEntry,"id"|"at">)=>setState(s=>({...s,audit:[{...entry,id:crypto.randomUUID(),at:new Date().toISOString()},...s.audit]}));
 const value=useMemo<Store>(()=>({state,hydrated,signIn:(mode)=>setState(s=>({...s,session:mode==="customer"?{name:"Sarah Mitchell",email:"sarah.mitchell@riverside.example",role:"Organisation Admin",orgId:"riverside",organisations:["riverside","northfield"]}:{name:"Alex Morgan",email:"alex.morgan@gpitservices.example",role:"Platform Owner",orgId:"riverside",organisations:["riverside","northfield"]}})),signOut:()=>setState(s=>({...s,session:null})),setRole:(role)=>setState(s=>s.session?{...s,session:{...s.session,role},audit:[{id:crypto.randomUUID(),at:new Date().toISOString(),actor:s.session.name,orgId:s.session.orgId,type:"Role change",objectRef:role,detail:`Prototype role changed to ${role}`},...s.audit]}:s),setOrg:(orgId)=>setState(s=>s.session?.organisations.includes(orgId)?{...s,session:{...s.session,orgId},audit:[{id:crypto.randomUUID(),at:new Date().toISOString(),actor:s.session.name,orgId,type:"Organisation switch",objectRef:orgId,detail:"Active organisation changed"},...s.audit]}:s),addTicket:(t)=>setState(s=>({...s,tickets:[t,...s.tickets]})),updateTicket:(id,fn)=>setState(s=>({...s,tickets:s.tickets.map(t=>t.id===id?fn(t):t)})),addUser:(u)=>setState(s=>({...s,users:[...s.users,u]})),updateUser:(id,fn)=>setState(s=>({...s,users:s.users.map(u=>u.id===id?fn(u):u)})),viewArticle:(id)=>setState(s=>({...s,recentArticles:[id,...s.recentArticles.filter(x=>x!==id)].slice(0,3)})),voteArticle:(id,v)=>setState(s=>({...s,articleVotes:{...s.articleVotes,[id]:v}})),setPreference:(k,v)=>setState(s=>({...s,[k]:v})),patchState:setState,addAudit:audit,resetDemo:()=>{localStorage.removeItem(KEY);setState(structuredClone(initialState))}}),[state,hydrated]);return <Ctx.Provider value={value}>{children}</Ctx.Provider>}
export function usePortal(){const v=useContext(Ctx);if(!v)throw new Error("PortalProvider missing");return v}
