import { Link,useNavigate } from "@tanstack/react-router";
import { Bell,BookOpen,Building2,ChevronDown,ClipboardList,HeartPulse,LayoutDashboard,LifeBuoy,LogOut,ShieldCheck,UserRound,Wrench } from "lucide-react";
import { usePortal } from "@/lib/portal-store";
import { organisations } from "@/data/portal-data";
import { isOperationsRole } from "@/lib/authorisation";
import logo from "@/assets/gpit-logo.png";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuLabel,DropdownMenuSeparator,DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import type { OrganisationId,Role } from "@/lib/portal-types";
import type { ReactNode } from "react";
const nav=[{to:"/dashboard",label:"Dashboard",icon:LayoutDashboard},{to:"/support",label:"Get Support",icon:LifeBuoy},{to:"/requests",label:"My Requests",icon:ClipboardList},{to:"/knowledge",label:"Knowledge",icon:BookOpen},{to:"/status",label:"Service Status",icon:HeartPulse},{to:"/organisation",label:"Organisation",icon:Building2},{to:"/profile",label:"Profile",icon:UserRound}] as const;
export function AppShell({children}:{children:ReactNode}){const{state,setRole,setOrg,signOut}=usePortal();const navigate=useNavigate();const s=state.session;if(!s)return null;const operations=isOperationsRole(s.role);return <div className="min-h-screen bg-background">
 <aside className="fixed inset-y-0 left-0 z-30 hidden w-64 border-r border-border bg-sidebar lg:flex lg:flex-col"><div className="flex h-20 items-center border-b border-sidebar-border px-6"><img src={logo} alt="GP IT Services" className="h-auto w-44"/></div><nav className="flex-1 space-y-1 p-3" aria-label="Primary">{nav.map(({to,label,icon:Icon})=><Link key={to} to={to} activeProps={{className:"bg-sidebar-accent text-sidebar-primary font-semibold"}} inactiveProps={{className:"text-sidebar-foreground hover:bg-sidebar-accent"}} className="flex min-h-11 items-center gap-3 rounded-md px-3 text-sm"><Icon className="size-5"/>{label}</Link>)}{operations&&<><p className="px-3 pt-5 pb-1 text-xs font-bold uppercase text-muted-foreground">Operations</p><Link to="/operations" activeProps={{className:"bg-sidebar-accent text-sidebar-primary font-semibold"}} className="flex min-h-11 items-center gap-3 rounded-md px-3 text-sm text-sidebar-foreground hover:bg-sidebar-accent"><Wrench className="size-5"/>Support operations</Link></>}</nav><div className="border-t border-sidebar-border p-4 text-xs text-muted-foreground">Autotask is the system of record.<br/>The portal is the secure customer-facing workflow layer.</div></aside>
 <div className="lg:pl-64"><header className="sticky top-0 z-20 flex min-h-20 items-center justify-between gap-3 border-b border-border bg-card px-4 sm:px-6 lg:px-8"><img src={logo} alt="GP IT Services" className="h-auto w-36 lg:hidden"/><div className="hidden min-w-0 sm:block"><p className="text-xs font-semibold uppercase text-muted-foreground">Current organisation</p><Select value={s.orgId} onValueChange={v=>setOrg(v as OrganisationId)}><SelectTrigger className="mt-1 min-h-11 w-[280px] border-0 bg-muted font-semibold"><SelectValue/></SelectTrigger><SelectContent>{s.organisations.map(id=><SelectItem key={id} value={id}>{organisations[id].name}</SelectItem>)}</SelectContent></Select></div><div className="flex items-center gap-1"><Button variant="ghost" size="icon" aria-label="Notifications"><Bell/></Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" className="gap-2"><span className="hidden text-left sm:block"><span className="block text-xs text-muted-foreground">Prototype role</span><span className="block max-w-36 truncate">{s.role}</span></span><ChevronDown/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-60"><DropdownMenuLabel>Switch prototype role</DropdownMenuLabel>{(["Organisation User","Organisation Admin","Support Analyst","Platform Owner"] as Role[]).map(r=><DropdownMenuItem key={r} onClick={()=>setRole(r)}>{r}</DropdownMenuItem>)}<DropdownMenuSeparator/><DropdownMenuItem onClick={()=>{signOut();navigate({to:"/",replace:true})}}><LogOut/>Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header>
 <div className="sm:hidden border-b border-border bg-card px-4 py-3"><Select value={s.orgId} onValueChange={v=>setOrg(v as OrganisationId)}><SelectTrigger className="min-h-11 w-full"><SelectValue/></SelectTrigger><SelectContent>{s.organisations.map(id=><SelectItem key={id} value={id}>{organisations[id].name}</SelectItem>)}</SelectContent></Select></div>{children}</div>
 <nav className="fixed inset-x-0 bottom-0 z-40 grid grid-cols-5 border-t border-border bg-card px-1 pb-[max(0.35rem,env(safe-area-inset-bottom))] lg:hidden" aria-label="Mobile primary">{nav.slice(0,5).map(({to,label,icon:Icon})=><Link key={to} to={to} activeProps={{className:"text-primary"}} inactiveProps={{className:"text-muted-foreground"}} className="flex min-h-16 flex-col items-center justify-center gap-1 text-[11px] font-medium"><Icon className="size-5"/><span className="truncate">{label}</span></Link>)}</nav></div>}
export function Protected({children}:{children:ReactNode}){const{state,hydrated}=usePortal();const navigate=useNavigate();if(!hydrated)return <div className="min-h-screen bg-background"/>;if(!state.session){queueMicrotask(()=>navigate({to:"/",replace:true}));return null}return <AppShell>{children}</AppShell>}